name: "test / js"

on:
  pull_request:
  push:
    branches:
      - main
      - 5.0-dev

env:
  CI: true
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
  NODE_OPTIONS: "--max-old-space-size=4096"

concurrency:
  group: "${{ github.event.pull_request.number }}-${{ github.ref_name }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  test-js:
    name: test-js
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        uses: "gradio-app/gradio/.github/actions/install-frontend-deps@main"
        with:
          always_install_pnpm: true
      - name: build client
        run: pnpm --filter @gradio/client build
      - name: build the wasm module
        run: pnpm --filter @gradio/wasm build
      - name: format check
        run: pnpm format:check
      - name: lint
        run: pnpm lint
      - name: typecheck
        run: pnpm ts:check
      - name: unit tests
        run: pnpm test:run
      - name: client tests
        run: pnpm --filter @gradio/client test
      
